### ISSUE TITLE
ESM build is not working

### ISSUE THREAD

**Issue by kasperpeulen** [shellscape/jsx-email#38] opened 2023-10-12 09:11 UTC
- Component or Package Name: `@jsx-email/all` (but for others the same apply)
- Component or Package Version: 2.0.2
- `@jsxp-email/cli` Version?: Not used
- Operating System (or Browser): OSX
- Node Version: v18.18.0
- Link to reproduction _(⚠️ read below)_:  https://stackblitz.com/edit/stackblitz-starters-ksqowi?file=index.js

### Expected Behavior

I should be able to run jsx-email in node in projects that are "type:module":
```json
{
  "type": "module",
  "dependencies": {
    "@jsx-email/all": "^2.0.1"
  }
}
```

### Actual Behavior
I get an error:
```bash
file:///Users/kasperpeulen/code/modern-web-app/bla.js:1
import {renderAsync} from '@jsx-email/all';
        ^^^^^^^^^^^
SyntaxError: Named export 'renderAsync' not found. The requested module '@jsx-email/all' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@jsx-email/all';
const {renderAsync} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.18.0
```
### Additional Information

I think this can be fixed by making sure that the ESM build outputs `.mjs` files.

<img width="698" alt="image" src="https://github.com/shellscape/jsx-email/assets/1035299/8677d2c7-b68c-4678-ae74-c897cd6de854">

I tried renaming the esm output files locally in node_modules and that worked.

**Comment by shellscape** [comment] 2023-10-12 11:35
This is not the fault of jsx-email. We export both ESM and CJS. Please fill out the entire issue template next time.

**Comment by kasperpeulen** [comment] 2023-10-12 12:20
Added a repro @shellscape

**Comment by shellscape** [comment] 2023-10-12 13:15
Your reproduction doesn't show an error on my end. Looks like it's working fine. 

<img width="706" alt="Screenshot 2023-10-12 at 9 15 00 AM" src="https://github.com/shellscape/jsx-email/assets/76371/ba60e107-838a-493a-82be-a928774f6cd7">

**Comment by kasperpeulen** [comment] 2023-10-12 14:07
@shellscape I added now a stackblitz start command (`node index.js`), you should see:
<img width="859" alt="image" src="https://github.com/shellscape/jsx-email/assets/1035299/a13bd1da-7647-4270-b2be-237988105b92">

**Comment by shellscape** [comment] 2023-10-12 19:09
OK thanks we'll take a look

**Comment by shellscape** [comment] 2023-10-13 00:22
I've managed to reproduce this locally. ESM is such a pain. It may be a bit before we roll out a fix for this, it requires altering how our build process works significantly. If you can use TypeScript, I'd recommend doing so.

**Comment by kasperpeulen** [comment] 2023-10-13 07:48
I think if you want to use typescript, the steps could be.

1. Place an extra `package.json` file in the `dist/es` directory. This avoid having to manually rename `js` files to `mjs` files.
2. Change the moduleResolution to `node16`
3. Add `.js` file extensions to all relative imports in the source code. For example:
`export * from './body.js';`

**Comment by shellscape** [comment] 2023-10-14 00:40
alright, we're going to completely change up our build process in the next few days which should resolve this.

**Closed** 2023-10-23 02:23 UTC

**Comment by shellscape** [comment] 2023-10-23 02:33
@kasperpeulen should be resolved down. cheers

**Comment by alexanderson1993** [comment] 2023-10-23 12:49
Hey, huge thanks for putting in the work to do this. You just unblocked me shipping the next version of my personal newsletter platform. Can't wait for my emails to look ✨ beautiful ✨!
